node('master') {

    def servicePrincipalId = 'AzureKubernetesId'
    def resourceGroup = 'RTDS-QA-RG'
    def aks = 'RTDSQAAKS'
    
    
    def dockerRegistry = 'rtdsqa.azurecr.io'
    
    def imageName = "todo-app:${env.BUILD_NUMBER}"
    env.IMAGE_TAG = "${dockerRegistry}/${imageName}"
    def dockerCredentialId = '	AzureContainerRegistryId'

    def currentEnvironment = 'blue'
    def newEnvironment = { ->
        currentEnvironment == 'blue' ? 'green' : 'blue'
    }

    stage('SCM') {
        checkout scm
    }

    stage('Build') {
        withCredentials([azureServicePrincipal('servicePrincipalId')]) {
            sh 'az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET -t $AZURE_TENANT_ID'
        }
    }
}
