node('master') {

    def servicePrincipalId = 'AzureKubernetesId'
    def resourceGroup = 'RTDS-QA-RG'
    def aks = 'RTDSQAAKS'
    
    
    def dockerRegistry = 'rtdsqa.azurecr.io'
    
    def imageName = "todo-app:${env.BUILD_NUMBER}"
    env.IMAGE_TAG = "${dockerRegistry}/${imageName}"
    def dockerCredentialId = 'AzureContainersRegistryId'

    def currentEnvironment = 'blue'
    def newEnvironment = { ->
        currentEnvironment == 'blue' ? 'green' : 'blue'
    }

    stage('SCM') {
        checkout scm
    }
    
    stage('Docker Image') {
        withDockerRegistry([credentialsId: dockerCredentialId, url: "https://${dockerRegistry}"]) {
            dir('target') {
                sh """
                    cp -f ../deploy/aks/Dockerfile .
                    docker build -t "${env.IMAGE_TAG}" .
                    docker push "${env.IMAGE_TAG}"
                """
            }
        }
    }
}
